mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
    path('follow/<int:user_pk>/', views.follow, name="follow"),
    path('<str:username>/', views.profile, name="profile"),
]

mysite/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/update/', views.update, name="update"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/comment_create/', views.comment_create, name="comment_create"),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name="comment_delete"),
    path('<int:article_pk>/like/', views.like, name="like"),
    path('<int:article_pk>/recommend/', views.recommend, name="recommend"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://kit.fontawesome.com/a2f029658b.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'accounts:profile' user.username %}">{{ user.username }}</a>
  {% endif %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link text-white" href="{% url 'articles:index' %}">게시판</a>
      {% if user.is_authenticated %}
        <a class="nav-item nav-link text-white" href="{% url 'articles:create' %}">CREATE</a>
        <a class="nav-item nav-link text-danger" href="{% url 'accounts:logout' %}">Logout</a>
      {% else %}
        <a class="nav-item nav-link text-white" href="{% url 'accounts:login' %}">LogIn</a>
        <a class="nav-item nav-link text-white" href="{% url 'accounts:signup' %}">SignUp</a>
      {% endif %}
    </div>
  </div>
</nav>

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message.message }}
    </div>
  {% endfor %}
{% endif %}
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  
  {% bootstrap_javascript jquery='full' %}
</body>
</html>